[project]
name = "missalounas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "flask>=3.1.2",
    "jq>=1.10.0",
    "jsonschema>=4.25.1",
    "requests>=2.32.3",
]

[tool.uv]
package = true

[tool.setuptools]
packages = ["app"]
